### ISSUE TITLE
Generating CSV files from official PDFs

### ISSUE THREAD

**Issue by dcabo** [correctiv/eurosfordoctors-dataharvest2017#1]
Hi @stefanw,

 We're looking at the repos related to Euros for Doctors, including the Django app and the Jupyter notebooks. It's all very good, thanks for making it public. Just one question: how did you generate the sample Poland CSV files from the [official PDFs][1]. Did you do it manually (unlocking the PDF, converting to Excel, removing unwanted rows and outputting to CSV) or do you have a script that does the work? The latter would make sense if there are many PDFs with the same format, but don't know if that was the case in Germany or Poland. (It doesn't seem to be the case in Spain, as far as we've seen.)

 thanks

[1]: http://eutransparency.abbvie.com/poland/web/2015_AbbVie_Poland_EFPIA_Report_Final.pdf

**Comment by stefanw** [comment]
Hi @dcabo,

it's mostly a manual process with some support from Tabula, in tough cases AbbyFineReader. The PDFs are all similar but still too different for one script and always needs manual checking, adjusting of rows etc. 

The `02_check_data.ipynb` contains a couple of checks that try to find inconsistencies in the data and may point to mistakes in conversion (or even in the original files).

[Here's the Google Sheet we use to track data and the template for the data files (has multiple sheets).](https://docs.google.com/spreadsheets/d/1fez19N6fzL8SsSSkcthMJOrsaW5DzM2xAJrVXPLaJEo/edit#gid=1262068430)

Cheers
Stefan

**Comment by dcabo** [comment]
Perfect, makes complete sense, thanks. 👍
